defaults: &defaults
  adapter: postgresql
  username: neosoft
  password: ac3r
  encoding: unicode
  pool: 5
  host: 127.0.0.1

development:
  <<: *defaults
  database: pinterest_development
test: &test
  <<: *defaults
  database: pinterest_test

production:
  <<: *defaults
  database: pinterest_production